# 1高斯模型

In [1]:
%matplotlib
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets   #从sklearn工具导入数据集

iris=datasets.load_iris()
print(iris.feature_names)
dir(iris)

Using matplotlib backend: Qt5Agg
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


['DESCR', 'data', 'feature_names', 'filename', 'target', 'target_names']

In [2]:
iris.target_names


array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [4]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [5]:
from sklearn.model_selection import train_test_split
iris_data_train, iris_data_test, iris_target_train,iris_target_test=train_test_split(iris.data,iris.target,test_size=0.3,random_state=25)

In [6]:
from sklearn.naive_bayes import GaussianNB
iris_model=GaussianNB()
iris_model.fit(iris_data_train,iris_target_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [7]:
result=iris_model.predict(iris_data_test)
np.corrcoef(result,iris_target_test)

array([[1.        , 0.94894007],
       [0.94894007, 1.        ]])

# 2多项式模型

In [8]:
from sklearn.datasets import fetch_20newsgroups
news=fetch_20newsgroups(subset="all")
print(news.keys())


dict_keys(['data', 'filenames', 'target_names', 'target', 'DESCR'])


In [9]:
print(news.data[35])
print(news.target[35])

From: UC525655@mizzou1.missouri.edu (M.Eaton)
Subject: (Q) Way to connect PB 145, IIsi, P LW LS?
Nntp-Posting-Host: mizzou1.missouri.edu
Organization: University of Missouri
Lines: 7

Is there a way to connect a PowerBook 145, Mac IIsi, and Personal LaserWriter
LS so that I can (not necessarily silmultaneoulsy) print from either the IIsi,
or PB, and file share between the IIsi and PB?
I know I can get the ($expensive$) LW NT upgrade for my LS, but I can't afford
that...
 
Thanks, Mark

4


In [10]:
news.target_names[3]

'comp.sys.ibm.pc.hardware'

In [11]:
news_train=fetch_20newsgroups(subset="train",remove=("headers","footers","quotes"))
news_test=fetch_20newsgroups(subset="test",remove=("headers","footers","quotes"))

In [12]:
from sklearn.feature_extraction.text import CountVectorizer
count_vect=CountVectorizer(stop_words="english",decode_error="ignore")
x_train=count_vect.fit_transform(news_train.data)

In [13]:
x_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import make_pipeline
from sklearn import metrics

pipe=make_pipeline(TfidfVectorizer(),MultinomialNB())
pipe.fit(news_train.data,news_train.target)
news_pred=pipe.predict(news_test.data)

print(metrics.classification_report(
        news_test.target,news_pred,target_names=news_test.target_names))

                          precision    recall  f1-score   support

             alt.atheism       0.81      0.07      0.13       319
           comp.graphics       0.72      0.62      0.67       389
 comp.os.ms-windows.misc       0.70      0.50      0.59       394
comp.sys.ibm.pc.hardware       0.55      0.75      0.64       392
   comp.sys.mac.hardware       0.81      0.61      0.69       385
          comp.windows.x       0.83      0.74      0.78       395
            misc.forsale       0.86      0.69      0.77       390
               rec.autos       0.82      0.68      0.74       396
         rec.motorcycles       0.89      0.63      0.73       398
      rec.sport.baseball       0.95      0.69      0.80       397
        rec.sport.hockey       0.59      0.90      0.71       399
               sci.crypt       0.47      0.80      0.59       396
         sci.electronics       0.77      0.43      0.55       393
                 sci.med       0.86      0.63      0.73       396
         

# 贝努利模型——离散数据

In [95]:
from sklearn.naive_bayes import BernoulliNB
X=np.random.randint(2,size=(6,100))
Y=np.array([0,1,2,3,4,5])
clf=BernoulliNB()
clf.fit(X,Y)
print(clf.predict(X[2:3]))


[2]


In [98]:
crime_train=pd.read_csv(r"C:\Users\Double2\Desktop\crime_train.csv\crime_train.csv",parse_dates=['Dates'])
crime_train.head()

Dates        Category                      Descript  \
0 2015-05-13 23:53:00        WARRANTS                WARRANT ARREST   
1 2015-05-13 23:53:00  OTHER OFFENSES      TRAFFIC VIOLATION ARREST   
2 2015-05-13 23:33:00  OTHER OFFENSES      TRAFFIC VIOLATION ARREST   
3 2015-05-13 23:30:00   LARCENY/THEFT  GRAND THEFT FROM LOCKED AUTO   
4 2015-05-13 23:30:00   LARCENY/THEFT  GRAND THEFT FROM LOCKED AUTO   

   DayOfWeek PdDistrict      Resolution                    Address  \
0  Wednesday   NORTHERN  ARREST, BOOKED         OAK ST / LAGUNA ST   
1  Wednesday   NORTHERN  ARREST, BOOKED         OAK ST / LAGUNA ST   
2  Wednesday   NORTHERN  ARREST, BOOKED  VANNESS AV / GREENWICH ST   
3  Wednesday   NORTHERN            NONE   1500 Block of LOMBARD ST   
4  Wednesday       PARK            NONE  100 Block of BRODERICK ST   

            X          Y  
0 -122.425892  37.774599  
1 -122.425892  37.774599  
2 -122.424363  37.800414  
3 -122.426995  37.800873  
4 -122.438738  37.771541

In [100]:
from sklearn import preprocessing
le= preprocessing.LabelEncoder()
crime=le.fit_transform(crime_train['Category'])


In [103]:
simple_le=preprocessing.LabelEncoder()
simple_le.fit(["soochow","shanghai","soochow","nanjing","shanghai"])
simple_le.classes_

array(['nanjing', 'shanghai', 'soochow'], dtype='<U8')

In [105]:
simple_le.transform(["soochow","shanghai","soochow","nanjing","shanghai"])

array([2, 1, 2, 0, 1], dtype=int64)

In [108]:
days=pd.get_dummies(crime_train['DayOfWeek'])
hour=crime_train['Dates'].dt.hour
hour=pd.get_dummies(hour)
district=pd.get_dummies(crime_train['PdDistrict'])

train_data=pd.concat([hour,days,district],axis=1)
train_data['crime']=crime
train_data.head()

0  1  2  3  4  5  6  7  8  9  ...  CENTRAL  INGLESIDE  MISSION  NORTHERN  \
0  0  0  0  0  0  0  0  0  0  0  ...        0          0        0         1   
1  0  0  0  0  0  0  0  0  0  0  ...        0          0        0         1   
2  0  0  0  0  0  0  0  0  0  0  ...        0          0        0         1   
3  0  0  0  0  0  0  0  0  0  0  ...        0          0        0         1   
4  0  0  0  0  0  0  0  0  0  0  ...        0          0        0         0   

   PARK  RICHMOND  SOUTHERN  TARAVAL  TENDERLOIN  crime  
0     0         0         0        0           0     37  
1     0         0         0        0           0     21  
2     0         0         0        0           0     21  
3     0         0         0        0           0     16  
4     1         0         0        0           0     16  

[5 rows x 42 columns]

In [109]:
crime_test=pd.read_csv(r"C:\Users\Double2\Desktop\crime_test.csv",parse_dates=['Dates'])
days=pd.get_dummies(crime_test['DayOfWeek'])
hour=crime_test['Dates'].dt.hour
hour=pd.get_dummies(hour)
district=pd.get_dummies(crime_test['PdDistrict'])

test_data=pd.concat([hour,days,district],axis=1)

In [111]:
from sklearn.naive_bayes import BernoulliNB
from sklearn.metrics import log_loss
features=train_data.columns.values[:-1]

training,testing=train_test_split(train_data,test_size=0.40)
bl_model=BernoulliNB()
bl_model.fit(training[features],training['crime'])
test_pred=bl_model.predict_proba(testing[features])
log_loss(testing['crime'],test_pred)

2.579914720117507